//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTrafficFreewayBR290.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTrafficFreewayBR290.Text.Header", typeof(Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 01.
        /// </summary>
        internal static string AverageFlowHour01 {
            get {
                return ResourceManager.GetString("AverageFlowHour01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 02.
        /// </summary>
        internal static string AverageFlowHour02 {
            get {
                return ResourceManager.GetString("AverageFlowHour02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 03.
        /// </summary>
        internal static string AverageFlowHour03 {
            get {
                return ResourceManager.GetString("AverageFlowHour03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 04.
        /// </summary>
        internal static string AverageFlowHour04 {
            get {
                return ResourceManager.GetString("AverageFlowHour04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 05.
        /// </summary>
        internal static string AverageFlowHour05 {
            get {
                return ResourceManager.GetString("AverageFlowHour05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 06.
        /// </summary>
        internal static string AverageFlowHour06 {
            get {
                return ResourceManager.GetString("AverageFlowHour06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 07.
        /// </summary>
        internal static string AverageFlowHour07 {
            get {
                return ResourceManager.GetString("AverageFlowHour07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 08.
        /// </summary>
        internal static string AverageFlowHour08 {
            get {
                return ResourceManager.GetString("AverageFlowHour08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 09.
        /// </summary>
        internal static string AverageFlowHour09 {
            get {
                return ResourceManager.GetString("AverageFlowHour09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 10.
        /// </summary>
        internal static string AverageFlowHour10 {
            get {
                return ResourceManager.GetString("AverageFlowHour10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 11.
        /// </summary>
        internal static string AverageFlowHour11 {
            get {
                return ResourceManager.GetString("AverageFlowHour11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio:12.
        /// </summary>
        internal static string AverageFlowHour12 {
            get {
                return ResourceManager.GetString("AverageFlowHour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 13.
        /// </summary>
        internal static string AverageFlowHour13 {
            get {
                return ResourceManager.GetString("AverageFlowHour13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 14.
        /// </summary>
        internal static string AverageFlowHour14 {
            get {
                return ResourceManager.GetString("AverageFlowHour14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 15.
        /// </summary>
        internal static string AverageFlowHour15 {
            get {
                return ResourceManager.GetString("AverageFlowHour15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 16.
        /// </summary>
        internal static string AverageFlowHour16 {
            get {
                return ResourceManager.GetString("AverageFlowHour16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 17.
        /// </summary>
        internal static string AverageFlowHour17 {
            get {
                return ResourceManager.GetString("AverageFlowHour17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 18.
        /// </summary>
        internal static string AverageFlowHour18 {
            get {
                return ResourceManager.GetString("AverageFlowHour18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 19.
        /// </summary>
        internal static string AverageFlowHour19 {
            get {
                return ResourceManager.GetString("AverageFlowHour19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 20.
        /// </summary>
        internal static string AverageFlowHour20 {
            get {
                return ResourceManager.GetString("AverageFlowHour20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 21.
        /// </summary>
        internal static string AverageFlowHour21 {
            get {
                return ResourceManager.GetString("AverageFlowHour21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 22.
        /// </summary>
        internal static string AverageFlowHour22 {
            get {
                return ResourceManager.GetString("AverageFlowHour22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 23.
        /// </summary>
        internal static string AverageFlowHour23 {
            get {
                return ResourceManager.GetString("AverageFlowHour23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Médio: 24.
        /// </summary>
        internal static string AverageFlowHour24 {
            get {
                return ResourceManager.GetString("AverageFlowHour24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxo Acumulado 12.
        /// </summary>
        internal static string FlowAccum12 {
            get {
                return ResourceManager.GetString("FlowAccum12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxo Acumulado 18.
        /// </summary>
        internal static string FlowAccum18 {
            get {
                return ResourceManager.GetString("FlowAccum18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxo Acumulado 24.
        /// </summary>
        internal static string FlowAccum24 {
            get {
                return ResourceManager.GetString("FlowAccum24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 01.
        /// </summary>
        internal static string TotalFlowHour01 {
            get {
                return ResourceManager.GetString("TotalFlowHour01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 02.
        /// </summary>
        internal static string TotalFlowHour02 {
            get {
                return ResourceManager.GetString("TotalFlowHour02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 03.
        /// </summary>
        internal static string TotalFlowHour03 {
            get {
                return ResourceManager.GetString("TotalFlowHour03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 04.
        /// </summary>
        internal static string TotalFlowHour04 {
            get {
                return ResourceManager.GetString("TotalFlowHour04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 05.
        /// </summary>
        internal static string TotalFlowHour05 {
            get {
                return ResourceManager.GetString("TotalFlowHour05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 06.
        /// </summary>
        internal static string TotalFlowHour06 {
            get {
                return ResourceManager.GetString("TotalFlowHour06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 07.
        /// </summary>
        internal static string TotalFlowHour07 {
            get {
                return ResourceManager.GetString("TotalFlowHour07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 08.
        /// </summary>
        internal static string TotalFlowHour08 {
            get {
                return ResourceManager.GetString("TotalFlowHour08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 09.
        /// </summary>
        internal static string TotalFlowHour09 {
            get {
                return ResourceManager.GetString("TotalFlowHour09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 10.
        /// </summary>
        internal static string TotalFlowHour10 {
            get {
                return ResourceManager.GetString("TotalFlowHour10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 11.
        /// </summary>
        internal static string TotalFlowHour11 {
            get {
                return ResourceManager.GetString("TotalFlowHour11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 12.
        /// </summary>
        internal static string TotalFlowHour12 {
            get {
                return ResourceManager.GetString("TotalFlowHour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 13.
        /// </summary>
        internal static string TotalFlowHour13 {
            get {
                return ResourceManager.GetString("TotalFlowHour13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 14.
        /// </summary>
        internal static string TotalFlowHour14 {
            get {
                return ResourceManager.GetString("TotalFlowHour14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 15.
        /// </summary>
        internal static string TotalFlowHour15 {
            get {
                return ResourceManager.GetString("TotalFlowHour15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 16.
        /// </summary>
        internal static string TotalFlowHour16 {
            get {
                return ResourceManager.GetString("TotalFlowHour16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 17.
        /// </summary>
        internal static string TotalFlowHour17 {
            get {
                return ResourceManager.GetString("TotalFlowHour17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 18.
        /// </summary>
        internal static string TotalFlowHour18 {
            get {
                return ResourceManager.GetString("TotalFlowHour18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 19.
        /// </summary>
        internal static string TotalFlowHour19 {
            get {
                return ResourceManager.GetString("TotalFlowHour19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 20.
        /// </summary>
        internal static string TotalFlowHour20 {
            get {
                return ResourceManager.GetString("TotalFlowHour20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total:21.
        /// </summary>
        internal static string TotalFlowHour21 {
            get {
                return ResourceManager.GetString("TotalFlowHour21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 22.
        /// </summary>
        internal static string TotalFlowHour22 {
            get {
                return ResourceManager.GetString("TotalFlowHour22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 23.
        /// </summary>
        internal static string TotalFlowHour23 {
            get {
                return ResourceManager.GetString("TotalFlowHour23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fluxo Total: 24.
        /// </summary>
        internal static string TotalFlowHour24 {
            get {
                return ResourceManager.GetString("TotalFlowHour24", resourceCulture);
            }
        }
    }
}
