//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTrafficFreewayBR290.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItensData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItensData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetTrafficFreewayBR290.Text.ItensData", typeof(ItensData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acumulado.
        /// </summary>
        internal static string Accumulated {
            get {
                return ResourceManager.GetString("Accumulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluxomedio.
        /// </summary>
        internal static string AverageFlow {
            get {
                return ResourceManager.GetString("AverageFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluxo.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluxoAcum12.
        /// </summary>
        internal static string FlowAccum12 {
            get {
                return ResourceManager.GetString("FlowAccum12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluxoAcum18.
        /// </summary>
        internal static string FlowAccum18 {
            get {
                return ResourceManager.GetString("FlowAccum18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluxoAcum24.
        /// </summary>
        internal static string FlowAccum24 {
            get {
                return ResourceManager.GetString("FlowAccum24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluxoData.
        /// </summary>
        internal static string FlowData {
            get {
                return ResourceManager.GetString("FlowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hora.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
